version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: husky
    versions:
    - ">= 5.a, < 6"
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.9.0
  - dependency-name: husky
    versions:
    - 4.3.8
  - dependency-name: stylelint-declaration-strict-value
    versions:
    - 1.7.7
  - dependency-name: lint-staged
    versions:
    - 10.5.3
